name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install
      - name: Output test report
        if: failure()
        run: cat target/surefire-reports/*.txt
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: fine-balm-425309-g1
          service_account_key: ${{ secrets.GCP_KEY }}

      - name: Deploy to GCP App Engine
        run: |
          gcloud app deploy app.yaml --quiet
          

